# Config for dashboard_05
data:
  input:
    dir: ./app/dash/data/input/
    project_data_template:
      selected: template_p1
      template_p1:
        description: Manually compiled data
        excels:
          1:
            name: manual_compiled_project_data.xlsx
            worksheets:
              - projects
    loan_data_template:
      selected: template_l2
      template_l1:
        description: Two Excel files from BTS
        excels:
          1:
            name: BTS_master_tables_20220606.xlsx
            worksheets:
              - tbl_company_grp
              - tbl_company
              - tbl_lender
          2:
            # name: BTS_loan_profile_20220606.xlsx
            name: BTS_loan_profile_20220606-testingdata.xlsx
            worksheets:
              - tbl_loan
              - tbl_facility
      template_l2:
        description: One Excel files from BTS
        excels:
          1:
            # name: BTS_tables_20220708.xlsx
            name: BTS_tables_20220708-testingdata.xlsx
            worksheets:
              - tbl_company_grp
              - tbl_company
              - tbl_lender
              - tbl_loan
              - tbl_loan_facility
  output:
    dir: ./app/dash/data/output/
    to_export:
      interim_output_csv: True
      master_output_csv: True

equity:
  amt_in_billion: 40.2

dates:
  day_zero:
    is_today: True
    date: 2022-06-15

uc_evergreen: True

matching_scheme:
  # TODO: Select the default matching scheme
  scheme_id: 4
  # The following 2 parameters applicable for Scheme 2 and 3 only (UC replacement)
  full_cover: False
  check_saving_by_area: True
  # The following 3 parameters applicable for Scheme 3 only (Revolver ceiling)
  revolver_ceiling: 5.0  # TODO: reset to 99999.0
  revolver_ceiling_for: loan_matching # Whether the ceiling is set for loan_matching or acquisition
  revolver_to_stay: max_cost  # Criteria of choose which revolver to stay for loan_matching or acquisition